import type { CategoryId, PreviewTemplateId } from "@/lib/preview-types";

export type NicheDef = {
  id: string;
  categoryId: CategoryId;
  label: string;
  templateId: PreviewTemplateId;
  /** Stored as config.archetypeId; each template interprets this string. */
  layoutId: string;
  defaultTagline: string;
  defaultServices: [string, string, string];
};

export const previewNiches: NicheDef[] = [
  // —— Products & retail
  {
    id: "retail-boutique-apparel",
    categoryId: "products",
    label: "Boutique / apparel",
    templateId: "retail",
    layoutId: "retail-browse",
    defaultTagline: "Style that fits Oklahoma life",
    defaultServices: ["New arrivals", "Personal styling", "Local pickup"],
  },
  {
    id: "retail-gift-shop",
    categoryId: "products",
    label: "Gift shop",
    templateId: "retail",
    layoutId: "retail-browse",
    defaultTagline: "Thoughtful gifts · Oklahoma made",
    defaultServices: ["Curated gifts", "Corporate bundles", "Seasonal collections"],
  },
  {
    id: "retail-furniture-showroom",
    categoryId: "products",
    label: "Furniture / showroom",
    templateId: "retail",
    layoutId: "retail-showroom",
    defaultTagline: "See it in person before you buy",
    defaultServices: ["Room sets", "Delivery & setup", "Design consult"],
  },
  {
    id: "retail-sporting-goods",
    categoryId: "products",
    label: "Sporting goods",
    templateId: "retail",
    layoutId: "retail-browse",
    defaultTagline: "Gear for every season",
    defaultServices: ["Team orders", "Equipment fit", "Local events"],
  },
  {
    id: "retail-electronics",
    categoryId: "products",
    label: "Electronics",
    templateId: "retail",
    layoutId: "retail-browse",
    defaultTagline: "Trusted tech · Straight answers",
    defaultServices: ["Repairs", "Business setups", "Warranty help"],
  },
  {
    id: "retail-farm-ranch",
    categoryId: "products",
    label: "Farm & ranch supply",
    templateId: "retail",
    layoutId: "retail-showroom",
    defaultTagline: "Supplies for working land",
    defaultServices: ["Feed & seed", "Equipment parts", "Bulk orders"],
  },
  {
    id: "retail-wholesale-b2b",
    categoryId: "products",
    label: "Wholesale / B2B counter",
    templateId: "retail",
    layoutId: "retail-browse",
    defaultTagline: "Reliable supply for your crew",
    defaultServices: ["Account pricing", "Will-call pickup", "Delivery routes"],
  },
  {
    id: "retail-hardware",
    categoryId: "products",
    label: "Hardware store",
    templateId: "retail",
    layoutId: "retail-showroom",
    defaultTagline: "What you need for the job",
    defaultServices: ["Cut-to-order", "Key cutting", "Tool rental"],
  },

  // —— Services & trades (HVAC-style / trades)
  {
    id: "svc-hvac",
    categoryId: "services",
    label: "HVAC",
    templateId: "hvac",
    layoutId: "hvac-emergency",
    defaultTagline: "Fast relief when Oklahoma weather turns",
    defaultServices: ["AC repair", "Heating repair", "Same-day service"],
  },
  {
    id: "svc-plumbing",
    categoryId: "services",
    label: "Plumbing",
    templateId: "hvac",
    layoutId: "hvac-emergency",
    defaultTagline: "Leaks stopped · Lines you can trust",
    defaultServices: ["Emergency service", "Water heaters", "Repipes"],
  },
  {
    id: "svc-electrical",
    categoryId: "services",
    label: "Electrical",
    templateId: "hvac",
    layoutId: "hvac-install",
    defaultTagline: "Safe installs · Code-conscious work",
    defaultServices: ["Panel upgrades", "EV chargers", "Lighting"],
  },
  {
    id: "svc-roofing",
    categoryId: "services",
    label: "Roofing",
    templateId: "hvac",
    layoutId: "hvac-emergency",
    defaultTagline: "Real timelines · Storm-ready crews",
    defaultServices: ["Inspections", "Repairs", "Replacements"],
  },
  {
    id: "svc-landscaping",
    categoryId: "services",
    label: "Landscaping / lawn",
    templateId: "hvac",
    layoutId: "hvac-install",
    defaultTagline: "Yards that hold up to Oklahoma heat",
    defaultServices: ["Maintenance", "Design installs", "Irrigation"],
  },
  {
    id: "svc-cleaning",
    categoryId: "services",
    label: "Cleaning (home or commercial)",
    templateId: "professional",
    layoutId: "pro-book",
    defaultTagline: "Consistent cleans · Clear scheduling",
    defaultServices: ["Recurring service", "Move-in/out", "Office cleaning"],
  },
  {
    id: "svc-pest",
    categoryId: "services",
    label: "Pest control",
    templateId: "hvac",
    layoutId: "hvac-emergency",
    defaultTagline: "Protect your home year-round",
    defaultServices: ["Interior & perimeter", "Termite", "Seasonal plans"],
  },
  {
    id: "svc-locksmith",
    categoryId: "services",
    label: "Locksmith",
    templateId: "hvac",
    layoutId: "hvac-emergency",
    defaultTagline: "Locked out? We’re on the way",
    defaultServices: ["Emergency unlock", "Rekey", "Commercial hardware"],
  },
  {
    id: "svc-auto-repair",
    categoryId: "services",
    label: "Auto repair / body",
    templateId: "professional",
    layoutId: "pro-expertise",
    defaultTagline: "Honest estimates · Quality work",
    defaultServices: ["Diagnostics", "Brakes & suspension", "Collision repair"],
  },
  {
    id: "svc-handyman",
    categoryId: "services",
    label: "Handyman",
    templateId: "hvac",
    layoutId: "hvac-install",
    defaultTagline: "Small jobs done right",
    defaultServices: ["Repairs", "Assembly", "Seasonal upkeep"],
  },
  {
    id: "svc-it-repair",
    categoryId: "services",
    label: "IT / computer repair",
    templateId: "professional",
    layoutId: "pro-expertise",
    defaultTagline: "Business tech without the jargon",
    defaultServices: ["On-site support", "Network setup", "Managed backups"],
  },

  // —— Services (trust / appointment — dental template family)
  {
    id: "svc-pet",
    categoryId: "services",
    label: "Pet grooming / veterinary",
    templateId: "dental",
    layoutId: "dental-family",
    defaultTagline: "Care your pets deserve",
    defaultServices: ["Wellness visits", "Grooming", "Urgent care"],
  },
  {
    id: "svc-fitness",
    categoryId: "services",
    label: "Fitness / gym",
    templateId: "professional",
    layoutId: "pro-book",
    defaultTagline: "Train on your schedule",
    defaultServices: ["Memberships", "Personal training", "Classes"],
  },
  {
    id: "svc-salon-spa",
    categoryId: "services",
    label: "Salon / spa",
    templateId: "dental",
    layoutId: "dental-cosmetic",
    defaultTagline: "Look and feel your best",
    defaultServices: ["Cuts & color", "Spa packages", "Bridal bookings"],
  },
  {
    id: "svc-photography",
    categoryId: "services",
    label: "Photography",
    templateId: "professional",
    layoutId: "pro-expertise",
    defaultTagline: "Moments captured with intention",
    defaultServices: ["Portraits", "Commercial shoots", "Event coverage"],
  },
  {
    id: "svc-legal",
    categoryId: "services",
    label: "Legal",
    templateId: "professional",
    layoutId: "pro-book",
    defaultTagline: "Clear guidance · Oklahoma-focused",
    defaultServices: ["Consultations", "Contracts", "Business law"],
  },
  {
    id: "svc-accounting",
    categoryId: "services",
    label: "Accounting / CPA",
    templateId: "professional",
    layoutId: "pro-book",
    defaultTagline: "Numbers organized · Taxes simplified",
    defaultServices: ["Bookkeeping", "Tax prep", "Payroll"],
  },
  {
    id: "svc-insurance",
    categoryId: "services",
    label: "Insurance agency",
    templateId: "professional",
    layoutId: "pro-book",
    defaultTagline: "Coverage that fits real life",
    defaultServices: ["Home & auto", "Business policies", "Claims help"],
  },
  {
    id: "svc-real-estate",
    categoryId: "services",
    label: "Real estate",
    templateId: "professional",
    layoutId: "pro-expertise",
    defaultTagline: "Local insight · Straight answers",
    defaultServices: ["Buyers", "Sellers", "Investors"],
  },
  {
    id: "svc-medical-clinic",
    categoryId: "services",
    label: "Medical clinic",
    templateId: "dental",
    layoutId: "dental-family",
    defaultTagline: "Care that respects your time",
    defaultServices: ["Same-week visits", "Chronic care", "Labs & imaging"],
  },
  {
    id: "svc-dental",
    categoryId: "services",
    label: "Dental practice",
    templateId: "dental",
    layoutId: "dental-family",
    defaultTagline: "Gentle care for every smile",
    defaultServices: ["Cleanings & exams", "Fillings & restorations", "Kids welcome"],
  },
  {
    id: "svc-counseling",
    categoryId: "services",
    label: "Counseling / therapy",
    templateId: "dental",
    layoutId: "dental-family",
    defaultTagline: "A calm space to reset",
    defaultServices: ["Individual", "Couples", "Telehealth"],
  },

  // —— Restaurants & food
  {
    id: "food-fine-dining",
    categoryId: "restaurants",
    label: "Fine dining",
    templateId: "restaurant",
    layoutId: "restaurant-reservations",
    defaultTagline: "An evening worth remembering",
    defaultServices: ["Chef’s tasting", "Wine pairings", "Private dining"],
  },
  {
    id: "food-casual-dining",
    categoryId: "restaurants",
    label: "Casual dining",
    templateId: "restaurant",
    layoutId: "restaurant-menu",
    defaultTagline: "Comfort food · Oklahoma hospitality",
    defaultServices: ["Family tables", "Daily specials", "Takeout"],
  },
  {
    id: "food-cafe",
    categoryId: "restaurants",
    label: "Café / coffee shop",
    templateId: "restaurant",
    layoutId: "restaurant-menu",
    defaultTagline: "Roasted fresh · Made in-house",
    defaultServices: ["Espresso bar", "Pastries", "Drive-thru"],
  },
  {
    id: "food-bar",
    categoryId: "restaurants",
    label: "Bar & lounge",
    templateId: "restaurant",
    layoutId: "restaurant-reservations",
    defaultTagline: "Craft drinks · Late-night energy",
    defaultServices: ["Cocktails", "Small plates", "Private events"],
  },
  {
    id: "food-bakery",
    categoryId: "restaurants",
    label: "Bakery & desserts",
    templateId: "restaurant",
    layoutId: "restaurant-menu",
    defaultTagline: "Baked daily in Oklahoma",
    defaultServices: ["Custom cakes", "Wholesale", "Catering trays"],
  },
  {
    id: "food-truck",
    categoryId: "restaurants",
    label: "Food truck / mobile",
    templateId: "restaurant",
    layoutId: "restaurant-menu",
    defaultTagline: "Find us on the street",
    defaultServices: ["Rotating locations", "Private events", "Festivals"],
  },
  {
    id: "food-catering",
    categoryId: "restaurants",
    label: "Catering",
    templateId: "restaurant",
    layoutId: "restaurant-reservations",
    defaultTagline: "Feeds that impress your guests",
    defaultServices: ["Corporate lunches", "Weddings", "Drop-off trays"],
  },
  {
    id: "food-hotel",
    categoryId: "restaurants",
    label: "Hotel / inn dining",
    templateId: "restaurant",
    layoutId: "restaurant-reservations",
    defaultTagline: "Stay, dine, unwind",
    defaultServices: ["Room service", "Breakfast buffet", "Banquets"],
  },
  {
    id: "food-fast-casual",
    categoryId: "restaurants",
    label: "Fast casual",
    templateId: "restaurant",
    layoutId: "restaurant-menu",
    defaultTagline: "Quick · Fresh · Local",
    defaultServices: ["Online ordering", "Rewards app", "Catering packs"],
  },
];

export function getNichesForCategory(categoryId: CategoryId): NicheDef[] {
  return previewNiches.filter((n) => n.categoryId === categoryId);
}

export function getNicheById(id: string): NicheDef | undefined {
  return previewNiches.find((n) => n.id === id);
}
